### ISSUE TITLE
Error in GridFTP Lite transfer mechanism

### ISSUE THREAD

**Issue by nawatts** [feltus/BDSS#147]
```
Traceback (most recent call last):
  File "/home/nwatts/.local/lib/python3.5/site-packages/client/transfer/data.py", line 53, in run_data_transfer
    (report.success, report.mechanism_output) = transfer.run(output_path)
  File "/home/nwatts/.local/lib/python3.5/site-packages/client/transfer/base.py", line 92, in run
    return self.mechanism.transfer_file(self.url, output_path, display_output)
  File "/home/nwatts/.local/lib/python3.5/site-packages/client/transfer/mechanisms/base.py", line 147, in transfer_file
    return run_subprocess(self.transfer_command(url, output_path), display_output)
  File "/home/nwatts/.local/lib/python3.5/site-packages/client/util.py", line 78, in run_subprocess
    universal_newlines=True)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1490, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: Can't convert 'int' object to str implicitly
```

Fix is to change `int` to `str` in `client/transfer/mechanisms/gridftp_lite.py`.

**Comment by nawatts** [comment]
Fixed this in client [1.0.1b2](https://testpypi.python.org/pypi/bdss-client/1.0.1b2)
