### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by spficklin** [feltus/BDSS#150]
When following the installation instructions I get the following error:
```
ficklin@ubuntu:~/Projects/BDSS/client$ pip3 install --editable .
Obtaining file:///home/ficklin/Projects/BDSS/client
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/home/ficklin/Projects/BDSS/client/setup.py", line 38, in <module>
        readme = open("README.rst", "r").read()
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ficklin/Projects/BDSS/client/setup.py", line 40, in <module>
        raise RuntimeError("Unable to read README.rst")
    RuntimeError: Unable to read README.rst
    
    ----------------------------------------
```
I got around it by creating the README.rst file.  It seems there's been a change somewhere and things weren't updated.

**Comment by nawatts** [comment]
With this monorepo containing both the client and metadata repository code, the main README file is at the root of the repository so that it is visible when someone views the repository on GitHub. However, that main README is also what I wanted to show on the PyPI page for the client (https://pypi.org/project/bdss-client/).

Thus, when publishing an update to PyPI, I link the main README.rst into the client directory (https://github.com/feltus/BDSS/blob/master/client/docs/developer/PublishUpdate.md#steps-to-publish). Since README.rst is what a user receives when they download the client from PyPI, setup.py references README.rst.

And in that, the workflow for an editable install from source was forgotten about and broken.
